import { NextRequest, NextResponse } from 'next/server'
import { readFileSync, existsSync } from 'fs'
import { join } from 'path'

export async function GET(
  _request: NextRequest,
  { params }: { params: Promise<{ slug: string }> }
) {
  const { slug } = await params

  // Sanitize slug to prevent path traversal
  const safeSlug = slug.replace(/[^a-z0-9-]/gi, '')

  // Pre-rendered PNGs are generated by scripts/regen-blog-svgs.mjs locally
  // (Vercel's serverless environment has no fonts installed, so on-the-fly
  // SVG-to-PNG conversion produces tofu boxes).
  const pngPath = join(process.cwd(), 'public', 'images', 'blog-og', `${safeSlug}.png`)

  if (!existsSync(pngPath)) {
    return new NextResponse('Not found', { status: 404 })
  }

  const pngBuffer = readFileSync(pngPath)

  return new NextResponse(pngBuffer as unknown as BodyInit, {
    headers: {
      'Content-Type': 'image/png',
      'Cache-Control': 'public, max-age=86400, s-maxage=604800, stale-while-revalidate=86400',
    },
  })
}
